### ISSUE TITLE
怎么经常报EOFError()  

### ISSUE THREAD

**Issue by flemington** [botvs/backtest_python#3]
调dll中的函数 getRecors() 就会报错
ret = self.lib.api_Exchange_GetRecords(self.ctx, self.idx, ctypes.c_long(period), ctypes.byref(r_len), ctypes.byref(buf_ptr))

返回 -2、
难道又与 python2.7有关系。 能否支持3.6？

**Comment by botvs** [comment]
EOF就是回测没历史数据或者回测结束
